---
abstract: 'do math with correct handling of significant figures'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
build_requires:
  Module::Build: '0.21'
  Test::Inter: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.21'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-SigFigs
provides:
  Math::SigFigs:
    file: lib/Math/SigFigs.pm
    version: '1.1'
requires:
  Carp: '0'
  perl: '5.006'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/SBECK-github/Math-SigFigs
version: '1.10'
