---
abstract: 'do math with correct handling of significant figures'
author:
  - 'Sullivan Beck (sbeck@cpan.org)'
build_requires:
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Find::Rule: '0'
  IO::File: '0'
  Test::Inter: '1.09'
  Test::More: '0'
  Test::Pod: '1.00'
  Test::Pod::Coverage: '1.00'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-SigFigs
no_index:
  directory:
    - t
    - inc
provides:
  Math::SigFigs:
    file: lib/Math/SigFigs.pm
    version: '1.21'
requires:
  Carp: '0'
  perl: '5.006'
resources:
  repository: git://github.com/SBECK-github/Math-SigFigs.git
version: '1.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
